AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  customerservice

  Sample SAM Template for customerservice

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        CUSTOMERS_TABLE: !Ref CustomersTable

Resources:
  CustomersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: customerservice
      Handler: customerservice.CustomerLambda::create
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CustomersTable
      Events:
        CustometEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customers
            Method: POST
  GetCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customerservice
      Handler: customerservice.CustomerLambda::read
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CustomersTable
      Events:
        CustometEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customers
            Method: GET

Outputs:
  CustomerServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for Customer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customers/"
  CustomerServiceFunction:
    Description: "CustomerServiceFunction Lambda Function ARN"
    Value: !GetAtt CreateCustomerFunction.Arn
  CustomerServiceFunctionIamRole:
    Description: "Implicit IAM Role created for CustomerService function"
    Value: !GetAtt CreateCustomerFunction.Arn
